package vim

import "testing"

func TestTextObjects(t *testing.T) {
	runOpCases(t, []opCase{
		// words
		{"diw", "foo b|ar baz", "diw", "foo | baz", "bar", Normal},
		{"ciw", "foo b|ar baz", "ciwX<esc>", "foo |X baz", "bar", Normal},
		{"ciw keeps insert", "foo b|ar baz", "ciw", "foo | baz", "bar", Insert},
		{"daw trailing blank", "foo b|ar baz", "daw", "foo |baz", "bar ", Normal},
		{"daw last word takes leading blank", "foo b|ar", "daw", "fo|o", " bar", Normal},
		{"diw on blanks", "foo |  bar", "diw", "foo|bar", "   ", Normal},
		{"daw on blanks", "foo |  bar baz", "daw", "foo| baz", "   bar", Normal},
		{"diw punct", "a.|..b", "diw", "a|b", "...", Normal},
		{"diW", "x a.|b y", "diW", "x | y", "a.b", Normal},
		{"daW", "x a.|b y", "daW", "x |y", "a.b ", Normal},
		{"d2iw", "|foo bar", "d2iw", "|bar", "foo ", Normal},
		{"d3iw", "|foo bar baz", "d3iw", "| baz", "foo bar", Normal},
		{"d2aw", "|a b c", "d2aw", "|c", "a b ", Normal},
		{"yiw", "foo b|ar", "yiw", "foo |bar", "bar", Normal},
		{"diw unicode", "x h|éllo y", "diw", "x | y", "héllo", Normal},
		{"diw empty line", "|", "diw", "|", "", Normal},
		// quotes
		{"di\"", `say "hel|lo" now`, `di"`, `say "|" now`, "hello", Normal},
		{"da\"", `say "hel|lo" now`, `da"`, `say |now`, `"hello" `, Normal},
		{"da\" at end takes leading", `say "hel|lo"`, `da"`, `sa|y`, ` "hello"`, Normal},
		{"ci\"", `x = "a|b"`, `ci"new<esc>`, `x = "ne|w"`, "ab", Normal},
		{"di\" on open quote", `a |"bc" d`, `di"`, `a "|" d`, "bc", Normal},
		{"di\" on close quote", `a "bc|" d`, `di"`, `a "|" d`, "bc", Normal},
		{"di\" before quotes", `|x "bc" d`, `di"`, `x "|" d`, "bc", Normal},
		{"di\" second string", `"a" x "b|c"`, `di"`, `"a" x "|"`, "bc", Normal},
		{"di\" empty", `x "|" y`, `ci"Z<esc>`, `x "|Z" y`, "", Normal},
		{"di\" escaped quote", `"a\"|b"`, `di"`, `"|"`, `a\"b`, Normal},
		{"di' single", "it 'is| ok'", "di'", "it '|'", "is ok", Normal},
		{"di` backtick", "run `l|s`", "di`", "run `|`", "ls", Normal},
		{"di\" no quotes", "|abc", `di"`, "|abc", "", Normal},
		// brackets
		{"di(", "f(a, |b)", "di(", "f(|)", "a, b", Normal},
		{"da(", "f(a, |b) x", "da(", "f| x", "(a, b)", Normal},
		{"dib", "f(a|b)", "dib", "f(|)", "ab", Normal},
		{"di)", "f(a|b)", "di)", "f(|)", "ab", Normal},
		{"di( on open", "f|(ab)", "di(", "f(|)", "ab", Normal},
		{"di( on close", "f(ab|)", "di(", "f(|)", "ab", Normal},
		{"di( nested", "f(a(b|)c)", "di(", "f(a(|)c)", "b", Normal},
		{"d2i( outer", "f(a(b|)c)", "d2i(", "f(|)", "a(b)c", Normal},
		{"di( across lines", "f(a,\n  |b)", "di(", "f(|)", "a,\n  b", Normal},
		{"di{ inner lines linewise", "if x {\n    f|oo\n    bar\n}", "di{", "if x {\n|}", "L:    foo\n    bar\n", Normal},
		{"ci{ inner lines", "if x {\n    f|oo\n}", "ci{X<esc>", "if x {\n    |X\n}", "L:    foo\n", Normal},
		{"da{ across lines", "a {\n  |b\n} c", "da{", "a | c", "{\n  b\n}", Normal},
		{"di[", "x[1|2]", "di[", "x[|]", "12", Normal},
		{"da[", "x[1|2]", "da[", "|x", "[12]", Normal},
		{"di]", "x[1|2]", "di]", "x[|]", "12", Normal},
		{"diB", "{a|b}", "diB", "{|}", "ab", Normal},
		{"di<", "<a|b>", "di<", "<|>", "ab", Normal},
		{"ci( empty", "f(|)", "ci(x<esc>", "f(|x)", "", Normal},
		{"di( not in block", "|abc", "di(", "|abc", "", Normal},
		{"yi(", "f(a|b)", "yi(", "f(|ab)", "ab", Normal},
		// paragraphs
		{"dap", "a\n|b\n\nc", "dap", "|c", "L:a\nb\n\n", Normal},
		{"dap takes all trailing blanks", "|a\n\n\nc", "dap", "|c", "L:a\n\n\n", Normal},
		{"dap last para takes leading blanks", "a\n\n|b\nc", "dap", "|a", "L:\nb\nc\n", Normal},
		{"dip", "a\n|b\n\nc", "dip", "|\nc", "L:a\nb\n", Normal},
		{"dip on blank run", "a\n\n|\nc", "dip", "a\n|c", "L:\n\n", Normal},
		{"dap on blank run", "a\n|\nb\nc\n\nd", "dap", "a\n|\nd", "L:\nb\nc\n", Normal},
		{"yap", "|a\nb\n\nc", "yap", "|a\nb\n\nc", "L:a\nb\n\n", Normal},
		{"cip", "x\n\n|a\nb\n\ny", "cipZ<esc>", "x\n\n|Z\n\ny", "L:a\nb\n", Normal},
		{"d2ip", "|a\n\nb", "d2ip", "|b", "L:a\n\n", Normal},
		{"d2ap", "|a\n\nb\n\nc", "d2ap", "|c", "L:a\n\nb\n\n", Normal},
		{"whitespace line is blank for ip", "|a\n  \nb", "dip", " | \nb", "L:a\n", Normal},
		{">ip", "|a\nb\n\nc", ">ip", "  |a\n  b\n\nc", "", Normal},
	})
}
